<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<!-- Meta tags Obrigatórias -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<!-- Estilo personalizado -->
		<link rel="stylesheet" type="text/css" href="css/menu-aula.css">

		<title>JavaScript</title>

		<script>
			/* Exemplo de erro para fazer o tratamento
			------------------------------------------*/
			var aVideos = Array()

			aVideos[1] = Array()
			aVideos[1]['nome'] = 'Fullmetal Alchemist'
			aVideos[1]['categoria'] = 'Anime'

			function obterVideo( aVideos ) {
				// comandos executados

				// força comportamento inesperado, pois o elemento definido é 1. O elemento 0 é indefinido (undefined)
				// este tipo de problema não interrompe a aplicação, verificar que a mensagem seguinte é apresentada.
				console.log( aVideos[0])
				console.log('A aplicação não morreu.')

				try {
					// força um erro de verdade, de execução, pois está tentando buscar o atributo de um objeto indefinido
					// este problema causa a interrupção do fluxo de execução. Verificar que a mensagem seguinte nem chega a ser apresentada.
					console.log( aVideos[0]['nome'])
					console.log('A aplicação ainda não morreu.')
				} catch(e) {
					console.log('Um erro ocorreu e não permite a finalização correta da aplicação.')
					console.log('Tratamento do erro: ' + 	e)
					throw new Error('O erro está sendo avaliado. Throw encerrará a aplicação. O Finally será executado.')
					console.log('Esta linha nem será exibida, pois o throw finalizou o catch. A execução irá para o finally.')

				} finally {
					console.log('Sempre passará por aqui (finally)')
				}

			}

			obterVideo( aVideos )

		</script>
	</head>
	<body>
		
		<div id="menu-aula" class="sticky-top">
			<h4>Javascript</h4>
			<ul class="nav nav-pills">
				<li class="nav-item"><a class="nav-link" href="variaveis.html">Variáveis</a></li>
				<li class="nav-item"><a class="nav-link" href="if-else.html">If-Else</a></li>
				<li class="nav-item"><a class="nav-link" href="switch.html">Switch..Case</a></li>
				<li class="nav-item"><a class="nav-link" href="operadores-aritmeticos.html">Operadores Aritméticos</a></li>
				<li class="nav-item"><a class="nav-link" href="funcoes.html">Funções</a></li>
				<li class="nav-item"><a class="nav-link" href="eventos.html">Eventos</a></li>
				<li class="nav-item"><a class="nav-link" href="dom.html">DOM - Document Object Model</a></li>
				<li class="nav-item"><a class="nav-link" href="exercicio1-dom.html">Exercício DOM</a></li>
				<li class="nav-item"><a class="nav-link" href="array.html">Arrays</a></li>
				<li class="nav-item"><a class="nav-link" href="exercicio2-array.html">Exercício Arrays</a></li>
				<li class="nav-item"><a class="nav-link" href="repeticoes.html">Estruturas de Repetição</a></li>
				<li class="nav-item"><a class="nav-link" href="try-catch.html">Tratamento de Erros</a></li>
				<li class="nav-item"><a class="nav-link" href="bom.html">BOM - Browser Object Model</a></li>
 			</ul>
		</div>

		<div class="conteudo">
			<h4>Tratamento de Erros</h4>
			<p>Possibilidade de tratamento de exceções que ocorram durante a execução dos códigos da página, por exemplo, apresentar uma página informativa de problemas, colocar alguma rotina de desvio da execução, etc.</p>
			<p>Encapsular os códigos que podem causar quebra na execução num bloco try..catch é uma maneira de evitar que a aplicação morra. </p>
			<p>O bloco try {...} encapsula os códigos que podem causar quebra na execução. Se um erro ocorre é possível executar uma ação de finalização da aplicação, ou tratamento do problema.</p>
			<p>O bloco finally {...} é o bloco que finaliza a execução do bloco de códigos que tentou ser executado e apresentou problemas.</p>
			<p>O catch(erro) {...} recebe o objeto erro e pode manipulá-lo, seja apresentado-o ou direcionando a execução para um fluxo de execução específico.</p>
			<p>Sintaxe básica: try { _comandos_de_execução_da_página } catch(erro) { _tratamento_do_erro_} finally {_saída_do_bloco}</p>
			<p>O bloco de código definido em finally sempre será executado, independente se um erro ocorreu ou não.</p>
			<p>O bloco de códigos throw {...} força uma parada abrupta da execução. Isso pode ser colocado no catch para que um tratamento do erro ocorra e aí sim a finalização do script ocorra.</p>
		</div>

		<!-- JavaScript (Opcional) -->
		<!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>